# Titanic

In [600]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
sns.set_style('whitegrid')
%matplotlib inline

In [701]:
train = pd.read_csv('train.csv')

In [702]:
test = pd.read_csv('test.csv')

In [703]:
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [704]:
test.head(10)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0  34.5      0      0     330911   7.8292   NaN        Q  
1  47.0      1      0     363272   7.0000   NaN        S  
2  62.0      0      0     240276   9.6875   NaN        Q  
3  27.0      0      0     315154   8.6625   NaN        S  
4  22.0      1      1    3101298  12.2875   NaN        S  
5  14.0      0      0       7538   9.2250   NaN        S  
6  30.0      0      0     330972   7.6292   NaN        Q  
7  26.0      1      1     248738  29.0000   NaN        S  
8  18.0      0      0       2657   7.2292   NaN        C  
9  21.0      2      0  A/4 48871  24.1500   NaN        S

In [705]:
# plt.figure(figsize=(12,6))
# sns.heatmap(train.isna())

In [706]:
# plt.figure(figsize=(12,6))
# sns.heatmap(test.isna())

In [707]:
# train['Age'].dropna().plot.hist(bins=25)

In [708]:
# test['Age'].dropna().plot.hist(bins=25)

In [709]:
train['Age'].fillna(train['Age'].dropna().median(),inplace=True)

In [710]:
test['Age'].fillna(test['Age'].dropna().median(),inplace=True)

In [711]:
# plt.figure(figsize=(12,6))
# sns.heatmap(train.isna())

In [712]:
# plt.figure(figsize=(12,6))
# sns.heatmap(test.isna())

In [713]:
train.drop('Cabin',axis=1,inplace=True)

In [714]:
test.drop('Cabin',axis=1,inplace=True)

In [715]:
train.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [716]:
test.isna().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

In [717]:
train.dropna(inplace=True)

In [718]:
train.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [745]:
test['Fare'][152]=test['Fare'].median(skipna=True)

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [746]:
test.isna().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [747]:
train.drop(['PassengerId','Ticket'],axis=1, inplace=True)
test.drop(['Ticket'],axis=1, inplace=True)

In [748]:
train.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch     Fare Embarked  
0    male  22.0      1      0   7.2500        S  
1  female  38.0      1      0  71.2833        C  
2  female  26.0      0      0   7.9250        S  
3  female  35.0      1      0  53.1000        S  
4    male  35.0      0      0   8.0500        S

In [749]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch     Fare Embarked  
0  34.5      0      0   7.8292        Q  
1  47.0      1      0   7.0000        S  
2  62.0      0      0   9.6875        Q  
3  27.0      0      0   8.6625        S  
4  22.0      1      1  12.2875        S

In [750]:
def is_alone(cols):
    Age=cols[0]
    sibsp = cols[1]
    parch = cols[2]
    if (sibsp + parch) == 0:
        if Age > 16:
            return 1
        else:
            return 0
    else: 
        return 0
    

In [751]:
train['Alone'] = train[['Age','SibSp','Parch']].apply(is_alone,axis=1)
test['Alone'] = test[['Age','SibSp','Parch']].apply(is_alone,axis=1)

In [752]:
train.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch     Fare Embarked  Alone  
0    male  22.0      1      0   7.2500        S      0  
1  female  38.0      1      0  71.2833        C      0  
2  female  26.0      0      0   7.9250        S      1  
3  female  35.0      1      0  53.1000        S      0  
4    male  35.0      0      0   8.0500        S      1

In [753]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch     Fare Embarked  Alone  
0  34.5      0      0   7.8292        Q      1  
1  47.0      1      0   7.0000        S      0  
2  62.0      0      0   9.6875        Q      1  
3  27.0      0      0   8.6625        S      1  
4  22.0      1      1  12.2875        S      0

In [754]:
train['title']=train['Name'].apply(lambda name: name.split(sep=',')[1].split(sep='.')[0].strip())
test['title'] =test['Name'].apply(lambda name: name.split(sep=',')[1].split(sep='.')[0].strip())

In [755]:
train.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch     Fare Embarked  Alone title  
0    male  22.0      1      0   7.2500        S      0    Mr  
1  female  38.0      1      0  71.2833        C      0   Mrs  
2  female  26.0      0      0   7.9250        S      1  Miss  
3  female  35.0      1      0  53.1000        S      0   Mrs  
4    male  35.0      0      0   8.0500        S      1    Mr

In [756]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch     Fare Embarked  Alone title  
0  34.5      0      0   7.8292        Q      1    Mr  
1  47.0      1      0   7.0000        S      0   Mrs  
2  62.0      0      0   9.6875        Q      1    Mr  
3  27.0      0      0   8.6625        S      1    Mr  
4  22.0      1      1  12.2875        S      0   Mrs

In [757]:
train.drop('Name', axis=1,inplace=True)
test.drop('Name', axis=1,inplace=True)

In [758]:
train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Alone title
0         0       3    male  22.0      1      0   7.2500        S      0    Mr
1         1       1  female  38.0      1      0  71.2833        C      0   Mrs
2         1       3  female  26.0      0      0   7.9250        S      1  Miss
3         1       1  female  35.0      1      0  53.1000        S      0   Mrs
4         0       3    male  35.0      0      0   8.0500        S      1    Mr

In [759]:
test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Alone  \
0          892       3    male  34.5      0      0   7.8292        Q      1   
1          893       3  female  47.0      1      0   7.0000        S      0   
2          894       2    male  62.0      0      0   9.6875        Q      1   
3          895       3    male  27.0      0      0   8.6625        S      1   
4          896       3  female  22.0      1      1  12.2875        S      0   

  title  
0    Mr  
1   Mrs  
2    Mr  
3    Mr  
4   Mrs

In [760]:
items=['Sex','Embarked']
for cols in items:
    add = pd.get_dummies(train[cols],drop_first=True)
    train=pd.concat([train,add], axis=1)

In [761]:
items=['Sex','Embarked']
for cols in items:
    add = pd.get_dummies(test[cols],drop_first=True)
    test=pd.concat([test,add], axis=1)

In [762]:
train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Alone  \
0         0       3    male  22.0      1      0   7.2500        S      0   
1         1       1  female  38.0      1      0  71.2833        C      0   
2         1       3  female  26.0      0      0   7.9250        S      1   
3         1       1  female  35.0      1      0  53.1000        S      0   
4         0       3    male  35.0      0      0   8.0500        S      1   

  title  male  Q  S  
0    Mr     1  0  1  
1   Mrs     0  0  0  
2  Miss     0  0  1  
3   Mrs     0  0  1  
4    Mr     1  0  1

In [763]:
test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Alone  \
0          892       3    male  34.5      0      0   7.8292        Q      1   
1          893       3  female  47.0      1      0   7.0000        S      0   
2          894       2    male  62.0      0      0   9.6875        Q      1   
3          895       3    male  27.0      0      0   8.6625        S      1   
4          896       3  female  22.0      1      1  12.2875        S      0   

  title  male  Q  S  
0    Mr     1  1  0  
1   Mrs     0  0  1  
2    Mr     1  1  0  
3    Mr     1  0  1  
4   Mrs     0  0  1

In [764]:
train.drop(items,axis=1,inplace=True)
train.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Alone title  male  Q  S
0         0       3  22.0      1      0   7.2500      0    Mr     1  0  1
1         1       1  38.0      1      0  71.2833      0   Mrs     0  0  0
2         1       3  26.0      0      0   7.9250      1  Miss     0  0  1
3         1       1  35.0      1      0  53.1000      0   Mrs     0  0  1
4         0       3  35.0      0      0   8.0500      1    Mr     1  0  1

In [765]:
test.drop(items,axis=1,inplace=True)
test.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare  Alone title  male  Q  S
0          892       3  34.5      0      0   7.8292      1    Mr     1  1  0
1          893       3  47.0      1      0   7.0000      0   Mrs     0  0  1
2          894       2  62.0      0      0   9.6875      1    Mr     1  1  0
3          895       3  27.0      0      0   8.6625      1    Mr     1  0  1
4          896       3  22.0      1      1  12.2875      0   Mrs     0  0  1

# Logistic Regression

In [772]:
train.drop('title',axis=1,inplace=True)

In [773]:
X= train.drop('Survived', axis=1)
y= train['Survived']

In [642]:
from sklearn.model_selection import train_test_split

In [643]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size =.3)

In [644]:
from sklearn.linear_model import LogisticRegression

In [645]:
lm = LogisticRegression()

In [646]:
lm.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [647]:
predictions = lm.predict(X_test)

In [648]:
from sklearn.metrics import classification_report,confusion_matrix

In [649]:
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

             precision    recall  f1-score   support

          0       0.86      0.84      0.85       173
          1       0.72      0.76      0.74        94

avg / total       0.81      0.81      0.81       267

[[145  28]
 [ 23  71]]


# Decision Trees

In [650]:
from sklearn.tree import DecisionTreeClassifier

In [651]:
dtree = DecisionTreeClassifier()

In [652]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [653]:
predictions = dtree.predict(X_test)

In [654]:
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

             precision    recall  f1-score   support

          0       0.84      0.80      0.82       173
          1       0.66      0.72      0.69        94

avg / total       0.78      0.77      0.77       267

[[138  35]
 [ 26  68]]


#   Random Forest

In [655]:
from sklearn.ensemble import RandomForestClassifier

In [656]:
rfc = RandomForestClassifier(n_estimators=20000)

In [657]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [658]:
predictions = rfc.predict(X_test)

In [659]:
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

             precision    recall  f1-score   support

          0       0.89      0.77      0.83       173
          1       0.66      0.82      0.73        94

avg / total       0.81      0.79      0.79       267

[[134  39]
 [ 17  77]]


# Support Vector Classifier

In [660]:
from sklearn.svm import SVC

In [661]:
model = SVC()

In [662]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [663]:
predictions = model.predict(X_test)

In [664]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[137  36]
 [ 38  56]]
             precision    recall  f1-score   support

          0       0.78      0.79      0.79       173
          1       0.61      0.60      0.60        94

avg / total       0.72      0.72      0.72       267



In [665]:
param_grid = {'C': [0.1,1, 10, 100, 1000,10000], 'gamma': [1,0.1,0.01,0.001,0.0001,.00001], 'kernel': ['rbf']} 

In [666]:
from sklearn.model_selection import GridSearchCV

In [667]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [668]:
# May take awhile!
grid.fit(X_train,y_train)

Fitting 3 folds for each of 36 candidates, totalling 108 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6057692307692307, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6038647342995169, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6038647342995169, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.6057692307692307, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.6038647342995169, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.6038647342995169, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...........................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  C=0.1, gamma=0.001, kernel=rbf, score=0.6231884057971014, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV]  C=0.1, gamma=0.001, kernel=rbf, score=0.6570048309178744, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV]  C=0.1, gamma=0.0001, kernel=rbf, score=0.6730769230769231, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV]  C=0.1, gamma=0.0001, kernel=rbf, score=0.6376811594202898, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV]  C=0.1, gamma=0.0001, kernel=rbf, score=0.6570048309178744, total=   0.0s
[CV] C=0.1, gamma=1e-05, kernel=rbf ..................................
[CV]  C=0.1, gamma=1e-05, kernel=rbf, score=0.6057692307692307, total=   0.0s
[CV] C=0.1, gamma=1e-05, kernel=rbf ..................................
[CV]  C=0.1, gamma=1e-05, kernel=rbf, score=0.5990338164251208, total=   0.0s
[CV] C=0.1, gamma=1e-05, 

[CV]  C=1000, gamma=1, kernel=rbf, score=0.5990338164251208, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.6538461538461539, total=   0.1s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.6135265700483091, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.714975845410628, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV]  C=1000, gamma=0.01, kernel=rbf, score=0.7451923076923077, total=   0.1s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV]  C=1000, gamma=0.01, kernel=rbf, score=0.6956521739130435, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV]  C=1000, gamma=0.01, kernel=rbf, score=0.7632850241545893, total=   0.1s
[CV] C=1000, gamma=0.001, kernel=rb

[Parallel(n_jobs=1)]: Done 108 out of 108 | elapsed:    5.8s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000, 10000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001, 1e-05], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [669]:
grid.best_params_

{'C': 10000, 'gamma': 1e-05, 'kernel': 'rbf'}

In [670]:
grid.best_estimator_

SVC(C=10000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1e-05, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [671]:
grid_predictions = grid.predict(X_test)

In [672]:
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[[149  24]
 [ 24  70]]
             precision    recall  f1-score   support

          0       0.86      0.86      0.86       173
          1       0.74      0.74      0.74        94

avg / total       0.82      0.82      0.82       267



# Scores

In [674]:
grid.score(X_test,y_test)

0.8202247191011236

In [675]:
lm.score(X_test,y_test)

0.8089887640449438

In [676]:
rfc.score(X_test,y_test)

0.79026217228464424

In [677]:
dtree.score(X_test,y_test)

0.77153558052434457

# Tensorflow

In [678]:
import tensorflow as tf
from sklearn import metrics


In [679]:
import tensorflow.contrib.learn as learn
feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(X_train)

In [680]:
 classifier = tf.contrib.learn.DNNClassifier(
      feature_columns=feature_columns, hidden_units=[10, 20, 10], n_classes=9)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c37065ba8>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmpkmrje9m1'}


In [681]:
  classifier.fit(X_train, y_train, steps=20000)


INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmpkmrje9m1/model.ckpt.
INFO:tensorflow:loss = 6.53925, step = 1
INFO:tensorflow:global_step/sec: 58.8393
INFO:tensorflow:loss = 0.589448, step = 101 (1.702 sec)
INFO:tensorflow:global_step/sec: 47.632
INFO:tensorflow:loss = 0.548356, step = 201 (2.098 sec)
INFO:tensorflow:global_step/sec: 50.2224
INFO:tensorflow:loss = 0.507877, step = 301 (1.991 sec)
INFO:tensorflow:global_step/sec: 71.2337
INFO:tensorflow:loss = 0.47931, step = 401 (1.404 sec)
INFO:tensorflow:global_step/sec: 72.6672
INFO:tensorflow:loss = 0.462034, step = 501 (1.377 sec)
INFO:tensorflow:global_step/sec: 73.1146
INFO:tensorflow:loss = 0.452198, step = 601 (1.367 sec)
INFO:tensorflow:global_step/sec: 72.2806
INFO:tensorflow:loss = 0.444383, step = 701 (1.383 sec)
INFO:tensorflow:global_step/sec: 73.2678
INFO:tensorflow:loss = 0.438472, step = 801 (1.364 sec)
INFO:tensorflow:global

INFO:tensorflow:global_step/sec: 66.5702
INFO:tensorflow:loss = 0.31769, step = 8201 (1.503 sec)
INFO:tensorflow:global_step/sec: 71.7095
INFO:tensorflow:loss = 0.319534, step = 8301 (1.394 sec)
INFO:tensorflow:global_step/sec: 70.6484
INFO:tensorflow:loss = 0.315253, step = 8401 (1.416 sec)
INFO:tensorflow:global_step/sec: 68.7453
INFO:tensorflow:loss = 0.314336, step = 8501 (1.454 sec)
INFO:tensorflow:global_step/sec: 72.3267
INFO:tensorflow:loss = 0.313446, step = 8601 (1.383 sec)
INFO:tensorflow:global_step/sec: 72.1183
INFO:tensorflow:loss = 0.313091, step = 8701 (1.386 sec)
INFO:tensorflow:global_step/sec: 69.525
INFO:tensorflow:loss = 0.315235, step = 8801 (1.438 sec)
INFO:tensorflow:global_step/sec: 71.6371
INFO:tensorflow:loss = 0.311591, step = 8901 (1.396 sec)
INFO:tensorflow:global_step/sec: 74.0592
INFO:tensorflow:loss = 0.311264, step = 9001 (1.351 sec)
INFO:tensorflow:global_step/sec: 73.2802
INFO:tensorflow:loss = 0.310819, step = 9101 (1.364 sec)
INFO:tensorflow:global

INFO:tensorflow:loss = 0.283811, step = 16501 (1.992 sec)
INFO:tensorflow:global_step/sec: 68.4555
INFO:tensorflow:loss = 0.284828, step = 16601 (1.460 sec)
INFO:tensorflow:global_step/sec: 70.7693
INFO:tensorflow:loss = 0.283288, step = 16701 (1.413 sec)
INFO:tensorflow:global_step/sec: 72.1449
INFO:tensorflow:loss = 0.284093, step = 16801 (1.386 sec)
INFO:tensorflow:global_step/sec: 71.1498
INFO:tensorflow:loss = 0.283087, step = 16901 (1.405 sec)
INFO:tensorflow:global_step/sec: 63.04
INFO:tensorflow:loss = 0.284289, step = 17001 (1.587 sec)
INFO:tensorflow:global_step/sec: 56.0574
INFO:tensorflow:loss = 0.320259, step = 17101 (1.785 sec)
INFO:tensorflow:global_step/sec: 62.9483
INFO:tensorflow:loss = 0.282898, step = 17201 (1.588 sec)
INFO:tensorflow:global_step/sec: 70.7691
INFO:tensorflow:loss = 0.303118, step = 17301 (1.412 sec)
INFO:tensorflow:global_step/sec: 71.5169
INFO:tensorflow:loss = 0.282299, step = 17401 (1.399 sec)
INFO:tensorflow:global_step/sec: 70.8358
INFO:tensorf

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x1c370652e8>, 'hidden_units': [10, 20, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=9, default_value=None, dtype=tf.float64, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x117eaa1e0>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [682]:
  predictions = list(classifier.predict(X_test, as_iterable=True))


INFO:tensorflow:Restoring parameters from /var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmpkmrje9m1/model.ckpt-20000


In [683]:
  score = metrics.accuracy_score(y_test, predictions)
  print('Accuracy: {0:f}'.format(score))


Accuracy: 0.801498


# 60/40 split

In [684]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X,y,test_size =.4)

In [685]:
lm = LogisticRegression()
lm.fit(X1_train,y1_train)
predictions = lm.predict(X1_test)
print(classification_report(y1_test, predictions))
print(confusion_matrix(y1_test, predictions))
lm.score(X1_test,y1_test)

             precision    recall  f1-score   support

          0       0.82      0.89      0.85       223
          1       0.78      0.68      0.73       133

avg / total       0.81      0.81      0.81       356

[[198  25]
 [ 43  90]]


0.8089887640449438

In [686]:
dtree = DecisionTreeClassifier()
dtree.fit(X1_train,y1_train)
predictions = dtree.predict(X1_test)
print(classification_report(y1_test, predictions))
print(confusion_matrix(y1_test, predictions))
dtree.score(X1_test,y1_test)

             precision    recall  f1-score   support

          0       0.84      0.89      0.86       223
          1       0.79      0.71      0.75       133

avg / total       0.82      0.82      0.82       356

[[198  25]
 [ 38  95]]


0.8230337078651685

In [687]:
rfc = RandomForestClassifier(n_estimators=20000)
rfc.fit(X1_train,y1_train)
predictions = rfc.predict(X1_test)
print(classification_report(y1_test, predictions))
print(confusion_matrix(y1_test, predictions))
rfc.score(X1_test,y1_test)

             precision    recall  f1-score   support

          0       0.86      0.91      0.88       223
          1       0.83      0.75      0.79       133

avg / total       0.85      0.85      0.85       356

[[202  21]
 [ 33 100]]


0.848314606741573

In [688]:
grid.fit(X1_train,y1_train)
grid.best_params_
grid.best_estimator_


Fitting 3 folds for each of 36 candidates, totalling 108 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6123595505617978, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6123595505617978, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6101694915254238, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.6123595505617978, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.6123595505617978, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.6101694915254238, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...........................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  C=0.1, gamma=0.001, kernel=rbf, score=0.6440677966101694, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV]  C=0.1, gamma=0.0001, kernel=rbf, score=0.6292134831460674, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV]  C=0.1, gamma=0.0001, kernel=rbf, score=0.6404494382022472, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV]  C=0.1, gamma=0.0001, kernel=rbf, score=0.632768361581921, total=   0.0s
[CV] C=0.1, gamma=1e-05, kernel=rbf ..................................
[CV]  C=0.1, gamma=1e-05, kernel=rbf, score=0.6123595505617978, total=   0.0s
[CV] C=0.1, gamma=1e-05, kernel=rbf ..................................
[CV]  C=0.1, gamma=1e-05, kernel=rbf, score=0.6123595505617978, total=   0.0s
[CV] C=0.1, gamma=1e-05, kernel=rbf ..................................
[CV]  C=0.1, gamma=1e-05, kernel=rbf, score=0.6101694915254238, total=   0.0s
[CV] C=1, gamma=1, kernel=

[CV]  C=1000, gamma=1, kernel=rbf, score=0.6179775280898876, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.5898876404494382, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.6045197740112994, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.6797752808988764, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.5842696629213483, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.6045197740112994, total=   0.0s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV]  C=1000, gamma=0.01, kernel=rbf, score=0.7191011235955056, total=   0.1s
[CV] C=1000, gamma=0.01, kernel=rbf ....

[Parallel(n_jobs=1)]: Done 108 out of 108 | elapsed:    4.9s finished


SVC(C=10000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1e-05, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [784]:
grid_predictions = grid.predict(X1_test)
print(confusion_matrix(y1_test,grid_predictions))
print(classification_report(y1_test,grid_predictions))
grid.score(X1_test,y1_test)

[[192  31]
 [ 41  92]]
             precision    recall  f1-score   support

          0       0.82      0.86      0.84       223
          1       0.75      0.69      0.72       133

avg / total       0.80      0.80      0.80       356



0.797752808988764

In [690]:
feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(X1_train)
classifier = tf.contrib.learn.DNNClassifier(
      feature_columns=feature_columns, hidden_units=[10, 20, 10], n_classes=9)
classifier.fit(X1_train, y1_train, steps=20000)


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c35bd5588>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmpld1p87h1'}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmpld1p87h1/model.ckpt.
INFO:tensorflow:loss = 16.5045, step = 1
INFO:tensorflow:global_step/sec: 78.6143
INFO:tensorflow:loss = 0.602068, s

INFO:tensorflow:loss = 0.360716, step = 7201 (1.311 sec)
INFO:tensorflow:global_step/sec: 74.2464
INFO:tensorflow:loss = 0.361019, step = 7301 (1.346 sec)
INFO:tensorflow:global_step/sec: 66.7928
INFO:tensorflow:loss = 0.360939, step = 7401 (1.497 sec)
INFO:tensorflow:global_step/sec: 81.7627
INFO:tensorflow:loss = 0.359632, step = 7501 (1.223 sec)
INFO:tensorflow:global_step/sec: 83.9977
INFO:tensorflow:loss = 0.359626, step = 7601 (1.191 sec)
INFO:tensorflow:global_step/sec: 81.9145
INFO:tensorflow:loss = 0.358352, step = 7701 (1.221 sec)
INFO:tensorflow:global_step/sec: 82.6495
INFO:tensorflow:loss = 0.358061, step = 7801 (1.211 sec)
INFO:tensorflow:global_step/sec: 86.5713
INFO:tensorflow:loss = 0.356295, step = 7901 (1.154 sec)
INFO:tensorflow:global_step/sec: 85.6147
INFO:tensorflow:loss = 0.354619, step = 8001 (1.169 sec)
INFO:tensorflow:global_step/sec: 85.7309
INFO:tensorflow:loss = 0.354089, step = 8101 (1.166 sec)
INFO:tensorflow:global_step/sec: 82.4417
INFO:tensorflow:loss

INFO:tensorflow:global_step/sec: 74.902
INFO:tensorflow:loss = 0.296635, step = 15601 (1.335 sec)
INFO:tensorflow:global_step/sec: 84.6482
INFO:tensorflow:loss = 0.299154, step = 15701 (1.181 sec)
INFO:tensorflow:global_step/sec: 86.608
INFO:tensorflow:loss = 0.301652, step = 15801 (1.154 sec)
INFO:tensorflow:global_step/sec: 85.4544
INFO:tensorflow:loss = 0.304504, step = 15901 (1.170 sec)
INFO:tensorflow:global_step/sec: 84.8004
INFO:tensorflow:loss = 0.301765, step = 16001 (1.180 sec)
INFO:tensorflow:global_step/sec: 84.0774
INFO:tensorflow:loss = 0.290241, step = 16101 (1.188 sec)
INFO:tensorflow:global_step/sec: 77.1812
INFO:tensorflow:loss = 0.294718, step = 16201 (1.296 sec)
INFO:tensorflow:global_step/sec: 64.3389
INFO:tensorflow:loss = 0.290169, step = 16301 (1.554 sec)
INFO:tensorflow:global_step/sec: 46.1257
INFO:tensorflow:loss = 0.290852, step = 16401 (2.170 sec)
INFO:tensorflow:global_step/sec: 48.4398
INFO:tensorflow:loss = 0.290122, step = 16501 (2.064 sec)
INFO:tensorf

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x1c37cc02e8>, 'hidden_units': [10, 20, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=9, default_value=None, dtype=tf.float64, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x117eaa1e0>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [691]:
predictions = list(classifier.predict(X1_test, as_iterable=True))
score = metrics.accuracy_score(y1_test, predictions)
print('Accuracy: {0:f}'.format(score))


INFO:tensorflow:Restoring parameters from /var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmpld1p87h1/model.ckpt-20000
Accuracy: 0.800562


In [774]:
X_actual_train = train.drop('Survived',axis=1)
# X_actual_train = X_actual_train.drop('Fare',axis=1)
y_actual_train = train['Survived']
X_actual_test = test.drop(['PassengerId','title'],axis=1).copy()
# X_actual_test = X_actual_test.drop('Fare',axis=1)



In [775]:
X_actual_train.head()

Pclass   Age  SibSp  Parch     Fare  Alone  male  Q  S
0       3  22.0      1      0   7.2500      0     1  0  1
1       1  38.0      1      0  71.2833      0     0  0  0
2       3  26.0      0      0   7.9250      1     0  0  1
3       1  35.0      1      0  53.1000      0     0  0  1
4       3  35.0      0      0   8.0500      1     1  0  1

In [776]:
lm = LogisticRegression()
lm.fit(X_actual_train,y_actual_train)
predictions = lm.predict(X_actual_test)

In [777]:
rfc.fit(X_train,y_train)
predictions1 = rfc.predict(X_actual_test)

In [778]:
submission = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": predictions1
    })


In [779]:
submission.to_csv('submission.csv', index=False)


In [780]:
submission1 = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": predictions
    })


In [783]:
submission1.to_csv('submission.csv', index=False)


In [787]:
grid_predictions = grid.predict(X_actual_test)
submission = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": grid_predictions
    })
submission.to_csv('submission.csv', index=False)


In [788]:
feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(X_actual_train)
classifier = tf.contrib.learn.DNNClassifier(
      feature_columns=feature_columns, hidden_units=[10, 20, 10], n_classes=9)
classifier.fit(X_actual_train, y_actual_train, steps=20000)
predictions = list(classifier.predict(X_actual_test, as_iterable=True))


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c363f7780>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmptvgle3ap'}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/0w/9c65zv0x3_v9t2mcg5rpj6580000gp/T/tmptvgle3ap/model.ckpt.
INFO:tensorflow:loss = 8.60128, step = 1
INFO:tensorflow:global_step/sec: 48.2558
INFO:tensorflow:loss = 0.615138, s

INFO:tensorflow:loss = 0.390583, step = 7201 (1.810 sec)
INFO:tensorflow:global_step/sec: 53.4558
INFO:tensorflow:loss = 0.39026, step = 7301 (1.871 sec)
INFO:tensorflow:global_step/sec: 53.9601
INFO:tensorflow:loss = 0.390422, step = 7401 (1.853 sec)
INFO:tensorflow:global_step/sec: 54.1738
INFO:tensorflow:loss = 0.3902, step = 7501 (1.846 sec)
INFO:tensorflow:global_step/sec: 55.6725
INFO:tensorflow:loss = 0.39004, step = 7601 (1.796 sec)
INFO:tensorflow:global_step/sec: 54.1287
INFO:tensorflow:loss = 0.389481, step = 7701 (1.847 sec)
INFO:tensorflow:global_step/sec: 54.0596
INFO:tensorflow:loss = 0.389026, step = 7801 (1.850 sec)
INFO:tensorflow:global_step/sec: 52.3932
INFO:tensorflow:loss = 0.388919, step = 7901 (1.908 sec)
INFO:tensorflow:global_step/sec: 54.6276
INFO:tensorflow:loss = 0.389097, step = 8001 (1.831 sec)
INFO:tensorflow:global_step/sec: 54.4293
INFO:tensorflow:loss = 0.389057, step = 8101 (1.837 sec)
INFO:tensorflow:global_step/sec: 46.37
INFO:tensorflow:loss = 0.3

INFO:tensorflow:global_step/sec: 55.325
INFO:tensorflow:loss = 0.372206, step = 15601 (1.807 sec)
INFO:tensorflow:global_step/sec: 54.4081
INFO:tensorflow:loss = 0.372803, step = 15701 (1.838 sec)
INFO:tensorflow:global_step/sec: 55.6704
INFO:tensorflow:loss = 0.371827, step = 15801 (1.797 sec)
INFO:tensorflow:global_step/sec: 53.2041
INFO:tensorflow:loss = 0.37207, step = 15901 (1.880 sec)
INFO:tensorflow:global_step/sec: 52.3232
INFO:tensorflow:loss = 0.370961, step = 16001 (1.911 sec)
INFO:tensorflow:global_step/sec: 54.2686
INFO:tensorflow:loss = 0.372078, step = 16101 (1.843 sec)
INFO:tensorflow:global_step/sec: 44.3818
INFO:tensorflow:loss = 0.370882, step = 16201 (2.254 sec)
INFO:tensorflow:global_step/sec: 51.7745
INFO:tensorflow:loss = 0.371248, step = 16301 (1.930 sec)
INFO:tensorflow:global_step/sec: 43.9941
INFO:tensorflow:loss = 0.370014, step = 16401 (2.273 sec)
INFO:tensorflow:global_step/sec: 53.2037
INFO:tensorflow:loss = 0.370708, step = 16501 (1.880 sec)
INFO:tensorf

In [789]:
submission1 = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": predictions
    })
submission1.to_csv('submission.csv', index=False)
